In [21]:
import pandas as pd
import matplotlib.pyplot as plt
import plotly
import plotly.plotly as py
import plotly.graph_objs as go
import plotly.tools 

plotly.tools.set_credentials_file(username='oevasquez832', api_key='FWMYajgBnfuOU6ZZNa2q')

plotly.offline.init_notebook_mode(connected=True)
df =  pd.read_csv('actors_genre_rating.csv')
df

,name,year,genre1,genre2,Metacritic,IMDB,Rotten Tomatoes
0,The Revenant,2015,Adventure,Drama,76,80,80
1,The Theory of Everything,2014,Biography,Drama,69,77,78
2,Dallas Buyers Club,2013,Biography,Drama,84,80,93
3,Lincoln,2012,Biography,Drama,86,74,90
4,The Artist,2011,Comedy,Drama,89,79,95
5,The King's Speech,2010,Biography,Drama,88,80,95
6,Crazy Heart,2009,Drama,Music,83,73,91
7,Milk,2008,Biography,Drama,84,76,94
8,There Will Be Blood,2007,Drama,NaN,93,81,91
9,The Last King of Scotland,2006,Biography,Drama,74,77,87
10,Capote,2005,Biography,Crime,88,74,90
11,Ray,2004,Biography,Drama,73,77,81
12,Mystic River,2003,Crime,Drama,84,80,87
13,The Pianist,2002,Biography,Drama,85,85,95
14,Training Day,2001,Crime,Drama,69,77,72
15,Gladiator,2000,Action,Drama,67,85,77
16,American Beauty,1999,Drama,Romance,86,84,88
17,Life Is Beautiful,1998,Comedy,Drama,59,86,80
18,As Good As It Gets,1997,Comedy,Drama,67,77,84
19,Shine,1996,Biography,Drama,87,77,91
20,Leaving Las Vegas,1995,Drama,Romance,82,76,90

In [43]:
data = [
    go.Bar(
        x=df['name'], # assign x as the dataframe column 'x'
        y=df['IMDB'],
        name = 'IMDB',
        marker=dict(
        color='rgb(0,0,255)',
        line=dict(
            color='rgb(8,48,107)',
            width=1.5)),
        opacity=0.6
    ),
    go.Bar(
        x=df['name'],
        y=df['Metacritic'],
        name = 'Metacritic',
        marker=dict(
        color='rgb(0,255,0)',
        line=dict(
            color='rgb(8,48,107)',
            width=1.5)),
        opacity=0.6
    ),
    go.Bar(
        x=df['name'],
        y=df['Rotten Tomatoes'],
        name = 'Rotten Tomatoes',
        marker=dict(
        color='rgb(255,0,0)',
        line=dict(
            color='rgb(8,48,107)',
            width=1.5)),
        opacity = 0.6
    )
]

layout = go.Layout(
    title='Best Picture Winners Ratings',
    
    yaxis=dict(
        title='Ratings (%)',
        titlefont=dict(
            family='Courier New, monospace',
            size=14,
            color='black'
        )
    )
    )  

# IPython notebook
# py.iplot(data, filename='pandas-bar-chart')



fig = go.Figure(data=data, layout=layout)

py.plot(fig, filename='pandas-bar-chart')

'https://plot.ly/~oevasquez832/1'